/* colors---- index */
const _a = 0;  // black
const _b = 1;  // white
const _c = 2;  // red
const _d = 3;  // green
const _e = 4;  // blue
const _f = 5;  // yellow
const _g = 6;  // #00ffff
const _h = 7;  // #ff00ff
const _i = 8;  // #bf9d85 clay
const _j = 9;  // #1a62ff samudro
const _k = 10; // golden #ffd700
const _l = 11; // #348C31 grass
const _m = 12;


const patterns = [
    [
        [_i, _i, _i, _i, _i, _i, _i, _i, _i, _i, _i, _i, _i, _i, _i],
        [_i, _i, _i, _i, _i, _i, _i, _i, _i, _i, _i, _i, _i, _i, _i],
        [_i, _i, _i, _i, _i, _i, _i, _i, _i, _i, _i, _i, _i, _i, _i],
        [_i, _i, _i, _i, _i, _i, _i, _i, _i, _i, _i, _i, _i, _i, _i],
        [_i, _i, _i, _i, _i, _i, _i, _i, _i, _i, _i, _i, _i, _i, _i],
        [_i, _i, _i, _i, _i, _i, _i, _i, _i, _i, _i, _i, _i, _i, _i],
        [_i, _i, _i, _i, _i, _i, _i, _i, _i, _i, _i, _i, _i, _i, _i],
        [_i, _i, _i, _i, _i, _i, _i, _i, _i, _i, _i, _i, _i, _i, _i],
        [_i, _i, _i, _i, _i, _i, _i, _i, _i, _i, _i, _i, _i, _i, _i],
        [_i, _i, _i, _i, _i, _i, _i, _i, _i, _i, _i, _i, _i, _i, _i],
        [_i, _i, _i, _i, _i, _i, _i, _i, _i, _i, _i, _i, _i, _i, _i],
        [_i, _i, _i, _i, _i, _i, _i, _i, _i, _i, _i, _i, _i, _i, _i],
        [_i, _i, _i, _i, _i, _i, _i, _i, _i, _i, _i, _i, _i, _i, _i],
        [_i, _i, _i, _i, _i, _i, _i, _i, _i, _i, _i, _i, _i, _i, _i],
        [_i, _i, _i, _i, _i, _i, _i, _i, _i, _i, _i, _i, _i, _i, _i],
     ],
     [
        [_l, _l, _l, _l, _l, _l, _l, _a, _i, _i, _i, _i, _i, _i, _i],
        [_l, _l, _l, _l, _l, _l, _l, _a, _i, _i, _i, _i, _i, _i, _i],
        [_l, _l, _l, _l, _l, _l, _l, _a, _i, _i, _i, _i, _i, _i, _i],
        [_l, _l, _l, _l, _l, _l, _l, _a, _i, _i, _i, _i, _i, _i, _i],
        [_l, _l, _l, _l, _l, _l, _l, _a, _i, _i, _i, _i, _i, _i, _i],
        [_l, _l, _l, _l, _l, _l, _a, _i, _i, _i, _i, _i, _i, _i, _i],
        [_l, _l, _l, _l, _l, _a, _i, _i, _i, _i, _i, _i, _i, _i, _i],
        [_a, _a, _a, _a, _a, _i, _i, _i, _i, _i, _i, _i, _i, _i, _i],
        [_i, _i, _i, _i, _i, _i, _i, _i, _i, _i, _i, _i, _i, _i, _i],
        [_i, _i, _i, _i, _i, _i, _i, _i, _i, _i, _i, _i, _i, _i, _i],
        [_i, _i, _i, _i, _i, _i, _i, _i, _i, _i, _i, _i, _i, _i, _i],
        [_i, _i, _i, _i, _i, _i, _i, _i, _i, _i, _i, _i, _i, _i, _i],
        [_i, _i, _i, _i, _i, _i, _i, _i, _i, _i, _i, _i, _i, _i, _i],
        [_i, _i, _i, _i, _i, _i, _i, _i, _i, _i, _i, _i, _i, _i, _i],
        [_i, _i, _i, _i, _i, _i, _i, _i, _i, _i, _i, _i, _i, _i, _i],
     ],
     [
        [_i, _i, _i, _i, _i, _i, _i, _a, _l, _l, _l, _l, _l, _l, _l],
        [_i, _i, _i, _i, _i, _i, _i, _a, _l, _l, _l, _l, _l, _l, _l],
        [_i, _i, _i, _i, _i, _i, _i, _a, _l, _l, _l, _l, _l, _l, _l],
        [_i, _i, _i, _i, _i, _i, _i, _a, _l, _l, _l, _l, _l, _l, _l],
        [_i, _i, _i, _i, _i, _i, _i, _a, _l, _l, _l, _l, _l, _l, _l],
        [_i, _i, _i, _i, _i, _i, _i, _a, _l, _l, _l, _l, _l, _l, _l],
        [_i, _i, _i, _i, _i, _i, _i, _a, _l, _l, _l, _l, _l, _l, _l],
        [_i, _i, _i, _i, _i, _i, _i, _a, _l, _l, _l, _l, _l, _l, _l],
        [_i, _i, _i, _i, _i, _i, _i, _a, _l, _l, _l, _l, _l, _l, _l],
        [_i, _i, _i, _i, _i, _i, _i, _a, _l, _l, _l, _l, _l, _l, _l],
        [_i, _i, _i, _i, _i, _i, _i, _a, _l, _l, _l, _l, _l, _l, _l],
        [_i, _i, _i, _i, _i, _i, _i, _a, _l, _l, _l, _l, _l, _l, _l],
        [_i, _i, _i, _i, _i, _i, _i, _a, _l, _l, _l, _l, _l, _l, _l],
        [_i, _i, _i, _i, _i, _i, _i, _a, _l, _l, _l, _l, _l, _l, _l],
        [_i, _i, _i, _i, _i, _i, _i, _a, _l, _l, _l, _l, _l, _l, _l],
     ],
     [
        [_i, _i, _i, _i, _i, _i, _i, _a, _l, _l, _l, _l, _l, _l, _l],
        [_i, _i, _i, _i, _i, _i, _i, _a, _l, _l, _l, _l, _l, _l, _l],
        [_i, _i, _i, _i, _i, _i, _i, _a, _l, _l, _l, _l, _l, _l, _l],
        [_i, _i, _i, _i, _i, _i, _i, _a, _l, _l, _l, _l, _l, _l, _l],
        [_i, _i, _i, _i, _i, _i, _i, _a, _l, _l, _l, _l, _l, _l, _l],
        [_i, _i, _i, _i, _i, _i, _i, _a, _l, _l, _l, _l, _l, _l, _l],
        [_i, _i, _i, _i, _i, _i, _a, _l, _l, _l, _l, _l, _l, _l, _l],
        [_a, _a, _a, _a, _a, _a, _l, _l, _l, _l, _l, _l, _l, _l, _l],
        [_l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l],
        [_l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l],
        [_l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l],
        [_l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l],
        [_l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l],
        [_l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l],
        [_l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l],
     ],
     [
        [_l, _l, _l, _l, _l, _l, _l, _a, _i, _i, _i, _i, _i, _i, _i],
        [_l, _l, _l, _l, _l, _l, _l, _a, _i, _i, _i, _i, _i, _i, _i],
        [_l, _l, _l, _l, _l, _l, _l, _a, _i, _i, _i, _i, _i, _i, _i],
        [_l, _l, _l, _l, _l, _l, _l, _a, _i, _i, _i, _i, _i, _i, _i],
        [_l, _l, _l, _l, _l, _l, _l, _a, _i, _i, _i, _i, _i, _i, _i],
        [_l, _l, _l, _l, _l, _l, _a, _i, _i, _i, _i, _i, _i, _i, _i],
        [_l, _l, _l, _l, _l, _a, _i, _i, _i, _i, _i, _i, _i, _i, _i],
        [_a, _a, _a, _a, _a, _i, _i, _i, _i, _i, _a, _a, _a, _a, _a],
        [_i, _i, _i, _i, _i, _i, _i, _i, _i, _a, _l, _l, _l, _l, _l],
        [_i, _i, _i, _i, _i, _i, _i, _i, _a, _l, _l, _l, _l, _l, _l],
        [_i, _i, _i, _i, _i, _i, _i, _a, _l, _l, _l, _l, _l, _l, _l],
        [_i, _i, _i, _i, _i, _i, _i, _a, _l, _l, _l, _l, _l, _l, _l],
        [_i, _i, _i, _i, _i, _i, _i, _a, _l, _l, _l, _l, _l, _l, _l],
        [_i, _i, _i, _i, _i, _i, _i, _a, _l, _l, _l, _l, _l, _l, _l],
        [_i, _i, _i, _i, _i, _i, _i, _a, _l, _l, _l, _l, _l, _l, _l],
     ],
     [
        [_j, _j, _j, _j, _j, _j, _j, _a, _l, _l, _l, _l, _l, _l, _l],
        [_j, _j, _j, _j, _j, _j, _j, _a, _l, _l, _l, _l, _l, _l, _l],
        [_j, _j, _j, _j, _j, _j, _j, _a, _l, _l, _l, _l, _l, _l, _l],
        [_j, _j, _j, _j, _j, _j, _j, _a, _l, _l, _l, _l, _l, _l, _l],
        [_j, _j, _j, _j, _j, _j, _j, _a, _l, _l, _l, _l, _l, _l, _l],
        [_j, _j, _j, _j, _j, _j, _j, _a, _l, _l, _l, _l, _l, _l, _l],
        [_j, _j, _j, _j, _j, _j, _a, _l, _l, _l, _l, _l, _l, _l, _l],
        [_a, _a, _a, _a, _a, _a, _l, _l, _l, _l, _l, _l, _l, _l, _l],
        [_l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l],
        [_l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l],
        [_l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l],
        [_l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l],
        [_l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l],
        [_l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l],
        [_l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l],
     ],
     [
        [_l, _l, _l, _l, _l, _l, _l, _a, _j, _j, _j, _j, _j, _j, _j],
        [_l, _l, _l, _l, _l, _l, _l, _a, _j, _j, _j, _j, _j, _j, _j],
        [_l, _l, _l, _l, _l, _l, _l, _a, _j, _j, _j, _j, _j, _j, _j],
        [_l, _l, _l, _l, _l, _l, _l, _a, _j, _j, _j, _j, _j, _j, _j],
        [_l, _l, _l, _l, _l, _l, _l, _a, _j, _j, _j, _j, _j, _j, _j],
        [_l, _l, _l, _l, _l, _l, _l, _a, _j, _j, _j, _j, _j, _j, _j],
        [_l, _l, _l, _l, _l, _l, _a, _j, _j, _j, _j, _j, _j, _j, _j],
        [_a, _a, _a, _a, _a, _a, _j, _j, _j, _j, _j, _j, _j, _j, _j],
        [_j, _j, _j, _j, _j, _j, _j, _j, _j, _j, _j, _j, _j, _j, _j],
        [_j, _j, _j, _j, _j, _j, _j, _j, _j, _j, _j, _j, _j, _j, _j],
        [_j, _j, _j, _j, _j, _j, _j, _j, _j, _j, _j, _j, _j, _j, _j],
        [_j, _j, _j, _j, _j, _j, _j, _j, _j, _j, _j, _j, _j, _j, _j],
        [_j, _j, _j, _j, _j, _j, _j, _j, _j, _j, _j, _j, _j, _j, _j],
        [_j, _j, _j, _j, _j, _j, _j, _j, _j, _j, _j, _j, _j, _j, _j],
        [_j, _j, _j, _j, _j, _j, _j, _j, _j, _j, _j, _j, _j, _j, _j],
     ],
     [
        [_j, _j, _j, _j, _j, _j, _j, _a, _l, _l, _l, _l, _l, _l, _l],
        [_j, _j, _j, _j, _j, _j, _j, _a, _l, _l, _l, _l, _l, _l, _l],
        [_j, _j, _j, _j, _j, _j, _j, _a, _l, _l, _l, _l, _l, _l, _l],
        [_j, _j, _j, _j, _j, _j, _j, _a, _l, _l, _l, _l, _l, _l, _l],
        [_j, _j, _j, _j, _j, _j, _j, _a, _l, _l, _l, _l, _l, _l, _l],
        [_j, _j, _j, _j, _j, _j, _j, _a, _l, _l, _l, _l, _l, _l, _l],
        [_j, _j, _j, _j, _j, _j, _j, _a, _l, _l, _l, _l, _l, _l, _l],
        [_j, _j, _j, _j, _j, _j, _j, _a, _l, _l, _l, _l, _l, _l, _l],
        [_j, _j, _j, _j, _j, _j, _j, _a, _l, _l, _l, _l, _l, _l, _l],
        [_j, _j, _j, _j, _j, _j, _j, _a, _l, _l, _l, _l, _l, _l, _l],
        [_j, _j, _j, _j, _j, _j, _j, _a, _l, _l, _l, _l, _l, _l, _l],
        [_j, _j, _j, _j, _j, _j, _j, _a, _l, _l, _l, _l, _l, _l, _l],
        [_j, _j, _j, _j, _j, _j, _j, _a, _l, _l, _l, _l, _l, _l, _l],
        [_j, _j, _j, _j, _j, _j, _j, _a, _l, _l, _l, _l, _l, _l, _l],
        [_j, _j, _j, _j, _j, _j, _j, _a, _l, _l, _l, _l, _l, _l, _l],
     ],
     [
        [_l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l],
        [_l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l],
        [_l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l],
        [_l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l],
        [_l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l],
        [_l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l],
        [_l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l],
        [_l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l],
        [_l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l],
        [_l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l],
        [_l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l],
        [_l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l],
        [_l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l],
        [_l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l],
        [_l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l],
     ],
     [
        [_j, _j, _j, _j, _j, _j, _j, _j, _j, _j, _j, _j, _j, _j, _j],
        [_j, _j, _j, _j, _j, _j, _j, _j, _j, _j, _j, _j, _j, _j, _j],
        [_j, _j, _j, _j, _j, _j, _j, _j, _j, _j, _j, _j, _j, _j, _j],
        [_j, _j, _j, _j, _j, _j, _j, _j, _j, _j, _j, _j, _j, _j, _j],
        [_j, _j, _j, _j, _j, _j, _j, _j, _j, _j, _j, _j, _j, _j, _j],
        [_j, _j, _j, _j, _j, _j, _j, _j, _j, _j, _j, _j, _j, _j, _j],
        [_j, _j, _j, _j, _j, _j, _j, _j, _j, _j, _j, _j, _j, _j, _j],
        [_j, _j, _j, _j, _j, _j, _j, _j, _j, _j, _j, _j, _j, _j, _j],
        [_j, _j, _j, _j, _j, _j, _j, _j, _j, _j, _j, _j, _j, _j, _j],
        [_j, _j, _j, _j, _j, _j, _j, _j, _j, _j, _j, _j, _j, _j, _j],
        [_j, _j, _j, _j, _j, _j, _j, _j, _j, _j, _j, _j, _j, _j, _j],
        [_j, _j, _j, _j, _j, _j, _j, _j, _j, _j, _j, _j, _j, _j, _j],
        [_j, _j, _j, _j, _j, _j, _j, _j, _j, _j, _j, _j, _j, _j, _j],
        [_j, _j, _j, _j, _j, _j, _j, _j, _j, _j, _j, _j, _j, _j, _j],
        [_j, _j, _j, _j, _j, _j, _j, _j, _j, _j, _j, _j, _j, _j, _j],
     ],
     [
        [_l, _l, _l, _l, _l, _l, _l, _a, _j, _j, _j, _j, _j, _j, _j],
        [_l, _l, _l, _l, _l, _l, _l, _a, _j, _j, _j, _j, _j, _j, _j],
        [_l, _l, _l, _l, _l, _l, _l, _a, _j, _j, _j, _j, _j, _j, _j],
        [_l, _l, _l, _l, _l, _l, _l, _a, _j, _j, _j, _j, _j, _j, _j],
        [_l, _l, _l, _l, _l, _l, _l, _a, _j, _j, _j, _j, _j, _j, _j],
        [_l, _l, _l, _l, _l, _l, _a, _j, _j, _j, _j, _j, _j, _j, _j],
        [_l, _l, _l, _l, _l, _a, _j, _j, _j, _j, _j, _j, _j, _j, _j],
        [_a, _a, _a, _a, _a, _j, _j, _j, _j, _j, _a, _a, _a, _a, _a],
        [_j, _j, _j, _j, _j, _j, _j, _j, _j, _a, _l, _l, _l, _l, _l],
        [_j, _j, _j, _j, _j, _j, _j, _j, _a, _l, _l, _l, _l, _l, _l],
        [_j, _j, _j, _j, _j, _j, _j, _a, _l, _l, _l, _l, _l, _l, _l],
        [_j, _j, _j, _j, _j, _j, _j, _a, _l, _l, _l, _l, _l, _l, _l],
        [_j, _j, _j, _j, _j, _j, _j, _a, _l, _l, _l, _l, _l, _l, _l],
        [_j, _j, _j, _j, _j, _j, _j, _a, _l, _l, _l, _l, _l, _l, _l],
        [_j, _j, _j, _j, _j, _j, _j, _a, _l, _l, _l, _l, _l, _l, _l],
     ],
     [
        [_j, _j, _j, _j, _j, _j, _j, _a, _l, _l, _l, _l, _l, _l, _l],
        [_j, _j, _j, _j, _j, _j, _j, _a, _l, _l, _l, _l, _l, _l, _l],
        [_j, _j, _j, _j, _j, _j, _j, _a, _l, _l, _l, _l, _l, _l, _l],
        [_j, _j, _j, _j, _j, _j, _j, _a, _l, _l, _l, _l, _l, _l, _l],
        [_j, _j, _j, _j, _j, _j, _j, _a, _l, _l, _l, _l, _l, _l, _l],
        [_j, _j, _j, _j, _j, _j, _a, _l, _l, _l, _l, _l, _l, _l, _l],
        [_j, _j, _j, _j, _j, _a, _l, _l, _l, _l, _l, _l, _l, _l, _l],
        [_a, _a, _a, _a, _a, _l, _l, _l, _l, _l, _a, _a, _a, _a, _a],
        [_l, _l, _l, _l, _l, _l, _l, _l, _l, _a, _i, _i, _i, _i, _i],
        [_l, _l, _l, _l, _l, _l, _l, _l, _a, _i, _i, _i, _i, _i, _i],
        [_l, _l, _l, _l, _l, _l, _l, _a, _i, _i, _i, _i, _i, _i, _i],
        [_l, _l, _l, _l, _l, _l, _l, _a, _i, _i, _i, _i, _i, _i, _i],
        [_l, _l, _l, _l, _l, _l, _l, _a, _i, _i, _i, _i, _i, _i, _i],
        [_l, _l, _l, _l, _l, _l, _l, _a, _i, _i, _i, _i, _i, _i, _i],
        [_l, _l, _l, _l, _l, _l, _l, _a, _i, _i, _i, _i, _i, _i, _i],
     ],
     [
        [_j, _j, _j, _j, _j, _f, _k, _k, _k, _f, _j, _j, _j, _j, _j],
        [_j, _j, _j, _j, _j, _f, _k, _k, _k, _f, _j, _j, _j, _j, _j],
        [_j, _j, _j, _j, _j, _f, _k, _k, _k, _f, _j, _j, _j, _j, _j],
        [_j, _j, _j, _j, _j, _f, _k, _k, _k, _f, _j, _j, _j, _j, _j],
        [_j, _j, _j, _j, _j, _f, _k, _k, _k, _f, _j, _j, _j, _j, _j],
        [_j, _j, _j, _j, _j, _f, _k, _k, _k, _f, _j, _j, _j, _j, _j],
        [_j, _j, _j, _j, _a, _f, _k, _k, _k, _a, _j, _j, _j, _j, _j],
        [_j, _j, _j, _j, _a, _f, _k, _k, _k, _a, _j, _j, _j, _j, _j],
        [_j, _j, _j, _j, _a, _f, _k, _k, _k, _a, _j, _j, _j, _j, _j],
        [_j, _j, _j, _j, _j, _f, _k, _k, _k, _f, _j, _j, _j, _j, _j],
        [_j, _j, _j, _j, _j, _f, _k, _k, _k, _f, _j, _j, _j, _j, _j],
        [_j, _j, _j, _j, _j, _f, _k, _k, _k, _f, _j, _j, _j, _j, _j],
        [_j, _j, _j, _j, _j, _f, _k, _k, _k, _f, _j, _j, _j, _j, _j],
        [_j, _j, _j, _j, _j, _f, _k, _k, _k, _f, _j, _j, _j, _j, _j],
        [_j, _j, _j, _j, _j, _f, _k, _k, _k, _f, _j, _j, _j, _j, _j],
     ],
     [
        [_l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l],
        [_l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l],
        [_l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l],
        [_l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l, _l],
        [_l, _l, _l, _l, _l, _l, _f, _f, _f, _l, _l, _l, _l, _l, _l],
        [_l, _l, _l, _l, _l, _f, _f, _k, _f, _f, _l, _l, _l, _l, _l],
        [_l, _l, _l, _l, _l, _f, _k, _k, _k, _f, _l, _l, _l, _l, _l],
        [_a, _a, _a, _a, _a, _f, _k, _k, _k, _f, _a, _a, _a, _a, _a],
        [_j, _j, _j, _j, _j, _f, _k, _k, _k, _f, _j, _j, _j, _j, _j],
        [_j, _j, _j, _j, _a, _f, _k, _k, _k, _a, _j, _j, _j, _j, _j],
        [_j, _j, _j, _j, _a, _f, _k, _k, _k, _a, _j, _j, _j, _j, _j],
        [_j, _j, _j, _j, _j, _f, _k, _k, _k, _f, _j, _j, _j, _j, _j],
        [_j, _j, _j, _j, _j, _f, _k, _k, _k, _f, _j, _j, _j, _j, _j],
        [_j, _j, _j, _j, _j, _f, _k, _k, _k, _f, _j, _j, _j, _j, _j],
        [_j, _j, _j, _j, _j, _f, _k, _k, _k, _f, _j, _j, _j, _j, _j],
     ],
     
]
// const patterns = [
//     [
//         [_a, _b, _a],
//         [_a, _b, _a],
//         [_a, _b, _a]
//     ],
//     [
//         [_a, _b, _a],
//         [_b, _b, _b],
//         [_a, _b, _a]
//     ],
//     [
//         [_a, _b, _a],
//         [_b, _b, _b],
//         [_a, _a, _a]
//     ],
//     [
//         [_a, _a, _a],
//         [_a, _a, _a],
//         [_a, _a, _a]
//     ] 
// ]