/* colors---- index */
const a = 0;  // black
const b = 1;  // white
const c = 2;  // red
const d = 3;  // green
const e = 4;  // blue
const f = 5;  // yellow
const g = 6;  // #00ffff
const h = 7;  // #ff00ff
const i = 8;  // #bf9d85 clay
const j = 9;  // #1a62ff samudro
const k = 10; // golden #ffd700
const l = 11; // #348C31 grass
const m = 12;  // #bab8b8 like gray
const n = 13;  // #202020 close to balck


const worldMap = [
    [
        [i, i, i, i, i, i, i, i, i, i, i, i, i, i, i],
        [i, i, i, i, i, i, i, i, i, i, i, i, i, i, i],
        [i, i, i, i, i, i, i, i, i, i, i, i, i, i, i],
        [i, i, i, i, i, i, i, i, i, i, i, i, i, i, i],
        [i, i, i, i, i, i, i, i, i, i, i, i, i, i, i],
        [i, i, i, i, i, i, i, i, i, i, i, i, i, i, i],
        [i, i, i, i, i, i, i, i, i, i, i, i, i, i, i],
        [i, i, i, i, i, i, i, i, i, i, i, i, i, i, i],
        [i, i, i, i, i, i, i, i, i, i, i, i, i, i, i],
        [i, i, i, i, i, i, i, i, i, i, i, i, i, i, i],
        [i, i, i, i, i, i, i, i, i, i, i, i, i, i, i],
        [i, i, i, i, i, i, i, i, i, i, i, i, i, i, i],
        [i, i, i, i, i, i, i, i, i, i, i, i, i, i, i],
        [i, i, i, i, i, i, i, i, i, i, i, i, i, i, i],
        [i, i, i, i, i, i, i, i, i, i, i, i, i, i, i],
     ],
     [
        [l, l, l, l, l, l, l, a, i, i, i, i, i, i, i],
        [l, l, l, l, l, l, l, a, i, i, i, i, i, i, i],
        [l, l, l, l, l, l, l, a, i, i, i, i, i, i, i],
        [l, l, l, l, l, l, l, a, i, i, i, i, i, i, i],
        [l, l, l, l, l, l, l, a, i, i, i, i, i, i, i],
        [l, l, l, l, l, l, a, i, i, i, i, i, i, i, i],
        [l, l, l, l, l, a, i, i, i, i, i, i, i, i, i],
        [a, a, a, a, a, i, i, i, i, i, i, i, i, i, i],
        [i, i, i, i, i, i, i, i, i, i, i, i, i, i, i],
        [i, i, i, i, i, i, i, i, i, i, i, i, i, i, i],
        [i, i, i, i, i, i, i, i, i, i, i, i, i, i, i],
        [i, i, i, i, i, i, i, i, i, i, i, i, i, i, i],
        [i, i, i, i, i, i, i, i, i, i, i, i, i, i, i],
        [i, i, i, i, i, i, i, i, i, i, i, i, i, i, i],
        [i, i, i, i, i, i, i, i, i, i, i, i, i, i, i],
     ],
     [
        [i, i, i, i, i, i, i, a, l, l, l, l, l, l, l],
        [i, i, i, i, i, i, i, a, l, l, l, l, l, l, l],
        [i, i, i, i, i, i, i, a, l, l, l, l, l, l, l],
        [i, i, i, i, i, i, i, a, l, l, l, l, l, l, l],
        [i, i, i, i, i, i, i, a, l, l, l, l, l, l, l],
        [i, i, i, i, i, i, i, a, l, l, l, l, l, l, l],
        [i, i, i, i, i, i, i, a, l, l, l, l, l, l, l],
        [i, i, i, i, i, i, i, a, l, l, l, l, l, l, l],
        [i, i, i, i, i, i, i, a, l, l, l, l, l, l, l],
        [i, i, i, i, i, i, i, a, l, l, l, l, l, l, l],
        [i, i, i, i, i, i, i, a, l, l, l, l, l, l, l],
        [i, i, i, i, i, i, i, a, l, l, l, l, l, l, l],
        [i, i, i, i, i, i, i, a, l, l, l, l, l, l, l],
        [i, i, i, i, i, i, i, a, l, l, l, l, l, l, l],
        [i, i, i, i, i, i, i, a, l, l, l, l, l, l, l],
     ],
     [
        [i, i, i, i, i, i, i, a, l, l, l, l, l, l, l],
        [i, i, i, i, i, i, i, a, l, l, l, l, l, l, l],
        [i, i, i, i, i, i, i, a, l, l, l, l, l, l, l],
        [i, i, i, i, i, i, i, a, l, l, l, l, l, l, l],
        [i, i, i, i, i, i, i, a, l, l, l, l, l, l, l],
        [i, i, i, i, i, i, i, a, l, l, l, l, l, l, l],
        [i, i, i, i, i, i, a, l, l, l, l, l, l, l, l],
        [a, a, a, a, a, a, l, l, l, l, l, l, l, l, l],
        [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
        [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
        [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
        [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
        [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
        [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
        [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
     ],
     [
        [l, l, l, l, l, l, l, a, i, i, i, i, i, i, i],
        [l, l, l, l, l, l, l, a, i, i, i, i, i, i, i],
        [l, l, l, l, l, l, l, a, i, i, i, i, i, i, i],
        [l, l, l, l, l, l, l, a, i, i, i, i, i, i, i],
        [l, l, l, l, l, l, l, a, i, i, i, i, i, i, i],
        [l, l, l, l, l, l, a, i, i, i, i, i, i, i, i],
        [l, l, l, l, l, a, i, i, i, i, i, i, i, i, i],
        [a, a, a, a, a, i, i, i, i, i, a, a, a, a, a],
        [i, i, i, i, i, i, i, i, i, a, l, l, l, l, l],
        [i, i, i, i, i, i, i, i, a, l, l, l, l, l, l],
        [i, i, i, i, i, i, i, a, l, l, l, l, l, l, l],
        [i, i, i, i, i, i, i, a, l, l, l, l, l, l, l],
        [i, i, i, i, i, i, i, a, l, l, l, l, l, l, l],
        [i, i, i, i, i, i, i, a, l, l, l, l, l, l, l],
        [i, i, i, i, i, i, i, a, l, l, l, l, l, l, l],
     ],
     [
        [j, j, j, j, j, j, j, a, l, l, l, l, l, l, l],
        [j, j, j, j, j, j, j, a, l, l, l, l, l, l, l],
        [j, j, j, j, j, j, j, a, l, l, l, l, l, l, l],
        [j, j, j, j, j, j, j, a, l, l, l, l, l, l, l],
        [j, j, j, j, j, j, j, a, l, l, l, l, l, l, l],
        [j, j, j, j, j, j, j, a, l, l, l, l, l, l, l],
        [j, j, j, j, j, j, a, l, l, l, l, l, l, l, l],
        [a, a, a, a, a, a, l, l, l, l, l, l, l, l, l],
        [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
        [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
        [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
        [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
        [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
        [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
        [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
     ],
     [
        [l, l, l, l, l, l, l, a, j, j, j, j, j, j, j],
        [l, l, l, l, l, l, l, a, j, j, j, j, j, j, j],
        [l, l, l, l, l, l, l, a, j, j, j, j, j, j, j],
        [l, l, l, l, l, l, l, a, j, j, j, j, j, j, j],
        [l, l, l, l, l, l, l, a, j, j, j, j, j, j, j],
        [l, l, l, l, l, l, l, a, j, j, j, j, j, j, j],
        [l, l, l, l, l, l, a, j, j, j, j, j, j, j, j],
        [a, a, a, a, a, a, j, j, j, j, j, j, j, j, j],
        [j, j, j, j, j, j, j, j, j, j, j, j, j, j, j],
        [j, j, j, j, j, j, j, j, j, j, j, j, j, j, j],
        [j, j, j, j, j, j, j, j, j, j, j, j, j, j, j],
        [j, j, j, j, j, j, j, j, j, j, j, j, j, j, j],
        [j, j, j, j, j, j, j, j, j, j, j, j, j, j, j],
        [j, j, j, j, j, j, j, j, j, j, j, j, j, j, j],
        [j, j, j, j, j, j, j, j, j, j, j, j, j, j, j],
     ],
     [
        [j, j, j, j, j, j, j, a, l, l, l, l, l, l, l],
        [j, j, j, j, j, j, j, a, l, l, l, l, l, l, l],
        [j, j, j, j, j, j, j, a, l, l, l, l, l, l, l],
        [j, j, j, j, j, j, j, a, l, l, l, l, l, l, l],
        [j, j, j, j, j, j, j, a, l, l, l, l, l, l, l],
        [j, j, j, j, j, j, j, a, l, l, l, l, l, l, l],
        [j, j, j, j, j, j, j, a, l, l, l, l, l, l, l],
        [j, j, j, j, j, j, j, a, l, l, l, l, l, l, l],
        [j, j, j, j, j, j, j, a, l, l, l, l, l, l, l],
        [j, j, j, j, j, j, j, a, l, l, l, l, l, l, l],
        [j, j, j, j, j, j, j, a, l, l, l, l, l, l, l],
        [j, j, j, j, j, j, j, a, l, l, l, l, l, l, l],
        [j, j, j, j, j, j, j, a, l, l, l, l, l, l, l],
        [j, j, j, j, j, j, j, a, l, l, l, l, l, l, l],
        [j, j, j, j, j, j, j, a, l, l, l, l, l, l, l],
     ],
     [
        [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
        [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
        [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
        [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
        [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
        [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
        [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
        [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
        [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
        [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
        [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
        [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
        [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
        [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
        [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
     ],
     [
        [j, j, j, j, j, j, j, j, j, j, j, j, j, j, j],
        [j, j, j, j, j, j, j, j, j, j, j, j, j, j, j],
        [j, j, j, j, j, j, j, j, j, j, j, j, j, j, j],
        [j, j, j, j, j, j, j, j, j, j, j, j, j, j, j],
        [j, j, j, j, j, j, j, j, j, j, j, j, j, j, j],
        [j, j, j, j, j, j, j, j, j, j, j, j, j, j, j],
        [j, j, j, j, j, j, j, j, j, j, j, j, j, j, j],
        [j, j, j, j, j, j, j, j, j, j, j, j, j, j, j],
        [j, j, j, j, j, j, j, j, j, j, j, j, j, j, j],
        [j, j, j, j, j, j, j, j, j, j, j, j, j, j, j],
        [j, j, j, j, j, j, j, j, j, j, j, j, j, j, j],
        [j, j, j, j, j, j, j, j, j, j, j, j, j, j, j],
        [j, j, j, j, j, j, j, j, j, j, j, j, j, j, j],
        [j, j, j, j, j, j, j, j, j, j, j, j, j, j, j],
        [j, j, j, j, j, j, j, j, j, j, j, j, j, j, j],
     ],
     [
        [l, l, l, l, l, l, l, a, j, j, j, j, j, j, j],
        [l, l, l, l, l, l, l, a, j, j, j, j, j, j, j],
        [l, l, l, l, l, l, l, a, j, j, j, j, j, j, j],
        [l, l, l, l, l, l, l, a, j, j, j, j, j, j, j],
        [l, l, l, l, l, l, l, a, j, j, j, j, j, j, j],
        [l, l, l, l, l, l, a, j, j, j, j, j, j, j, j],
        [l, l, l, l, l, a, j, j, j, j, j, j, j, j, j],
        [a, a, a, a, a, j, j, j, j, j, a, a, a, a, a],
        [j, j, j, j, j, j, j, j, j, a, l, l, l, l, l],
        [j, j, j, j, j, j, j, j, a, l, l, l, l, l, l],
        [j, j, j, j, j, j, j, a, l, l, l, l, l, l, l],
        [j, j, j, j, j, j, j, a, l, l, l, l, l, l, l],
        [j, j, j, j, j, j, j, a, l, l, l, l, l, l, l],
        [j, j, j, j, j, j, j, a, l, l, l, l, l, l, l],
        [j, j, j, j, j, j, j, a, l, l, l, l, l, l, l],
     ],
     [
        [j, j, j, j, j, j, j, a, l, l, l, l, l, l, l],
        [j, j, j, j, j, j, j, a, l, l, l, l, l, l, l],
        [j, j, j, j, j, j, j, a, l, l, l, l, l, l, l],
        [j, j, j, j, j, j, j, a, l, l, l, l, l, l, l],
        [j, j, j, j, j, j, j, a, l, l, l, l, l, l, l],
        [j, j, j, j, j, j, a, l, l, l, l, l, l, l, l],
        [j, j, j, j, j, a, l, l, l, l, l, l, l, l, l],
        [a, a, a, a, a, l, l, l, l, l, a, a, a, a, a],
        [l, l, l, l, l, l, l, l, l, a, i, i, i, i, i],
        [l, l, l, l, l, l, l, l, a, i, i, i, i, i, i],
        [l, l, l, l, l, l, l, a, i, i, i, i, i, i, i],
        [l, l, l, l, l, l, l, a, i, i, i, i, i, i, i],
        [l, l, l, l, l, l, l, a, i, i, i, i, i, i, i],
        [l, l, l, l, l, l, l, a, i, i, i, i, i, i, i],
        [l, l, l, l, l, l, l, a, i, i, i, i, i, i, i],
     ],
     [
        [j, j, j, j, j, f, k, k, k, f, j, j, j, j, j],
        [j, j, j, j, j, f, k, k, k, f, j, j, j, j, j],
        [j, j, j, j, j, f, k, k, k, f, j, j, j, j, j],
        [j, j, j, j, j, f, k, k, k, f, j, j, j, j, j],
        [j, j, j, j, j, f, k, k, k, f, j, j, j, j, j],
        [j, j, j, j, j, f, k, k, k, f, j, j, j, j, j],
        [j, j, j, j, a, f, k, k, k, f, a, j, j, j, j],
        [j, j, j, j, a, f, k, k, k, f, a, j, j, j, j],
        [j, j, j, j, a, f, k, k, k, f, a, j, j, j, j],
        [j, j, j, j, j, f, k, k, k, f, j, j, j, j, j],
        [j, j, j, j, j, f, k, k, k, f, j, j, j, j, j],
        [j, j, j, j, j, f, k, k, k, f, j, j, j, j, j],
        [j, j, j, j, j, f, k, k, k, f, j, j, j, j, j],
        [j, j, j, j, j, f, k, k, k, f, j, j, j, j, j],
        [j, j, j, j, j, f, k, k, k, f, j, j, j, j, j],
     ],
     [
        [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
        [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
        [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
        [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
        [l, l, l, l, l, l, f, f, f, l, l, l, l, l, l],
        [l, l, l, l, l, f, f, k, f, f, l, l, l, l, l],
        [l, l, l, l, l, f, k, k, k, f, l, l, l, l, l],
        [a, a, a, a, a, f, k, k, k, f, a, a, a, a, a],
        [j, j, j, j, j, f, k, k, k, f, j, j, j, j, j],
        [j, j, j, j, a, f, k, k, k, f, a, j, j, j, j],
        [j, j, j, j, a, f, k, k, k, f, a, j, j, j, j],
        [j, j, j, j, j, f, k, k, k, f, j, j, j, j, j],
        [j, j, j, j, j, f, k, k, k, f, j, j, j, j, j],
        [j, j, j, j, j, f, k, k, k, f, j, j, j, j, j],
        [j, j, j, j, j, f, k, k, k, f, j, j, j, j, j],
     ],
     
]

const PCBMap = [
   [
      [n, n, n, n, n, n, n, n, n, n, n, n, n, n, n],
      [n, n, n, n, n, n, n, n, n, n, n, n, n, n, n],
      [n, n, n, n, n, n, n, n, n, n, n, n, n, n, n],
      [n, n, n, n, n, n, n, n, n, n, n, n, n, n, n],
      [n, n, n, n, n, n, n, n, n, n, n, n, n, n, n],
      [n, n, n, n, n, n, n, n, n, n, n, n, n, n, n],
      [n, n, n, n, n, n, n, n, n, n, n, n, n, n, n],
      [n, n, n, n, n, n, n, n, n, n, n, n, n, n, n],
      [n, n, n, n, n, n, n, n, n, n, n, n, n, n, n],
      [n, n, n, n, n, n, n, n, n, n, n, n, n, n, n],
      [n, n, n, n, n, n, n, n, n, n, n, n, n, n, n],
      [n, n, n, n, n, n, n, n, n, n, n, n, n, n, n],
      [n, n, n, n, n, n, n, n, n, n, n, n, n, n, n],
      [n, n, n, n, n, n, n, n, n, n, n, n, n, n, n],
      [n, n, n, n, n, n, n, n, n, n, n, n, n, n, n], 
   ],
   [
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l], 
   ],
   [
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, a, a, a, a, a, a, a, l, l, l, l],
      [l, l, l, a, a, m, m, m, m, m, a, a, l, l, l],
      [l, l, a, a, m, m, m, m, m, m, m, a, a, l, l],
      [l, a, a, m, m, m, m, m, m, m, m, m, a, a, a],
      [l, a, m, m, m, m, m, m, m, m, m, m, m, a, g],
      [l, a, m, m, m, m, m, m, m, m, m, m, m, a, g],
      [l, a, m, m, m, m, m, m, m, m, m, m, m, a, g],
      [l, a, m, m, m, m, m, m, m, m, m, m, m, a, g],
      [l, a, m, m, m, m, m, m, m, m, m, m, m, a, g],
      [l, a, a, m, m, m, m, m, m, m, m, m, a, a, a],
      [l, l, a, a, m, m, m, m, m, m, m, a, a, l, l],
      [l, l, l, a, a, m, m, m, m, m, a, a, l, l, l],
      [l, l, l, l, a, a, a, a, a, a, a, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l], 
   ],
   [
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [a, a, a, a, a, a, a, a, a, a, a, a, a, a, a],
      [m, m, m, m, m, m, m, m, m, m, m, m, m, m, m],
      [m, m, m, m, m, m, m, m, m, m, m, m, m, m, m],
      [m, m, m, m, m, m, m, m, m, m, m, m, m, m, m],
      [m, m, m, m, m, m, m, m, m, m, m, m, m, m, m],
      [m, m, m, m, m, m, m, m, m, m, m, m, m, m, m],
      [a, a, a, a, a, a, a, a, a, a, a, a, a, a, a],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l], 
   ],
   [
      [n, n, a, l, l, l, l, l, l, l, l, l, l, l, l],
      [n, n, a, l, l, l, l, l, l, l, l, l, l, l, l],
      [n, n, a, a, a, a, a, l, l, l, l, l, l, l, l],
      [n, n, a, m, m, a, a, a, a, a, a, a, a, l, l],
      [n, n, a, m, m, a, m, m, m, m, m, m, a, a, a],
      [n, n, a, m, m, a, m, m, m, m, m, m, a, g, g],
      [n, n, a, m, m, a, m, m, m, m, m, m, a, g, g],
      [n, n, a, m, m, a, m, m, m, m, m, m, a, g, g],
      [n, n, a, m, m, a, m, m, m, m, m, m, a, g, g],
      [n, n, a, m, m, a, m, m, m, m, m, m, a, g, g],
      [n, n, a, m, m, a, m, m, m, m, m, m, a, a, a],
      [n, n, a, m, m, a, a, a, a, a, a, a, a, l, l],
      [n, n, a, a, a, a, a, l, l, l, l, l, l, l, l],
      [n, n, a, l, l, l, l, l, l, l, l, l, l, l, l],
      [n, n, a, l, l, l, l, l, l, l, l, l, l, l, l], 
   ],
   [
      [n, n, a, l, l, l, l, l, l, l, l, l, l, l, l],
      [n, n, a, l, l, l, l, l, l, l, l, l, l, l, l],
      [a, a, a, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l], 
   ],
   [
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [a, a, a, a, a, a, a, a, a, a, a, a, a, a, a],
      [g, g, g, g, g, g, g, g, g, g, g, g, g, g, g],
      [g, g, g, g, g, g, g, g, g, g, g, g, g, g, g],
      [g, g, g, g, g, g, g, g, g, g, g, g, g, g, g],
      [g, g, g, g, g, g, g, g, g, g, g, g, g, g, g],
      [g, g, g, g, g, g, g, g, g, g, g, g, g, g, g],
      [a, a, a, a, a, a, a, a, a, a, a, a, a, a, a],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l], 
   ],
   [
      [l, l, l, l, a, m, m, m, m, m, a, l, l, l, l],
      [l, l, l, l, a, m, m, m, m, m, a, l, l, l, l],
      [l, l, l, l, a, m, m, m, m, m, a, l, l, l, l],
      [l, l, l, l, a, m, m, m, m, m, a, l, l, l, l],
      [a, a, a, a, a, m, m, m, m, m, a, a, a, a, a],
      [g, g, g, g, a, m, m, m, m, m, a, g, g, g, g],
      [g, g, g, g, a, m, m, m, m, m, a, g, g, g, g],
      [g, g, g, g, a, m, m, m, m, m, a, g, g, g, g],
      [g, g, g, g, a, m, m, m, m, m, a, g, g, g, g],
      [g, g, g, g, a, m, m, m, m, m, a, g, g, g, g],
      [a, a, a, a, a, m, m, m, m, m, a, a, a, a, a],
      [l, l, l, l, a, m, m, m, m, m, a, l, l, l, l],
      [l, l, l, l, a, m, m, m, m, m, a, l, l, l, l],
      [l, l, l, l, a, m, m, m, m, m, a, l, l, l, l],
      [l, l, l, l, a, m, m, m, m, m, a, l, l, l, l], 
   ],
   [
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, a, a, a, a, a, a, a, a, a, l, l, l],
      [l, l, a, a, m, m, m, m, m, m, m, a, a, l, l],
      [a, a, a, m, m, a, a, a, a, a, a, a, a, a, a],
      [m, m, m, m, m, m, m, m, m, m, m, m, m, a, g],
      [m, m, m, m, m, m, m, m, m, m, m, m, m, a, g],
      [m, m, m, m, m, m, m, m, m, m, m, m, m, a, g],
      [m, m, m, m, m, m, m, m, m, m, m, m, m, a, g],
      [m, m, m, m, m, m, m, m, m, m, m, m, m, a, g],
      [a, a, a, m, m, a, a, a, a, a, a, a, a, a, a],
      [l, l, a, a, m, m, m, m, m, m, m, a, a, l, l],
      [l, l, l, a, a, a, a, a, a, a, a, a, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l], 
   ],
   [
      [l, l, l, l, a, g, g, g, g, g, a, l, l, l, l],
      [l, l, l, l, a, g, g, g, g, g, a, l, l, l, l],
      [l, l, l, l, a, g, g, g, g, g, a, l, l, l, l],
      [l, l, l, l, a, g, g, g, g, g, a, l, l, l, l],
      [a, a, a, a, a, g, g, g, g, g, a, a, a, a, a],
      [g, g, g, g, g, g, g, g, g, g, g, g, g, g, g],
      [g, g, g, g, g, g, g, g, g, g, g, g, g, g, g],
      [g, g, g, g, g, g, g, g, g, g, g, g, g, g, g],
      [g, g, g, g, g, g, g, g, g, g, g, g, g, g, g],
      [g, g, g, g, g, g, g, g, g, g, g, g, g, g, g],
      [a, a, a, a, a, a, a, a, a, a, a, a, a, a, a],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l], 
   ],
   [
      [l, l, l, l, a, g, g, g, g, g, a, l, l, l, l],
      [l, l, l, l, a, g, g, g, g, g, a, l, l, l, l],
      [l, l, l, l, a, g, g, g, g, g, a, l, l, l, l],
      [l, l, l, l, a, g, g, g, g, g, a, l, l, l, l],
      [l, l, l, l, a, g, g, g, g, g, a, a, a, a, a],
      [l, l, l, l, a, g, g, g, g, g, g, g, g, g, g],
      [l, l, l, l, a, g, g, g, g, g, g, g, g, g, g],
      [l, l, l, l, a, g, g, g, g, g, g, g, g, g, g],
      [l, l, l, l, a, g, g, g, g, g, g, g, g, g, g],
      [l, l, l, l, a, g, g, g, g, g, g, g, g, g, g],
      [l, l, l, l, a, a, a, a, a, a, a, a, a, a, a],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l], 
   ],
   [
      [l, l, l, l, a, g, g, g, g, g, a, l, l, l, l],
      [l, l, l, l, a, a, g, g, g, g, a, a, l, l, l],
      [l, l, l, l, l, a, a, g, g, g, g, a, a, l, l],
      [l, l, l, l, l, l, a, a, g, g, g, g, a, a, l],
      [a, a, l, l, l, l, l, a, a, g, g, g, g, a, a],
      [g, a, a, l, l, l, l, l, a, a, g, g, g, g, g],
      [g, g, a, a, l, l, l, l, l, a, a, g, g, g, g],
      [g, g, g, a, a, l, l, l, l, l, a, a, g, g, g],
      [g, g, g, g, a, a, l, l, l, l, l, a, a, g, g],
      [g, g, g, g, g, a, a, l, l, l, l, l, a, a, g],
      [a, a, g, g, g, g, a, a, l, l, l, l, l, a, a],
      [l, a, a, g, g, g, g, a, a, l, l, l, l, l, l],
      [l, l, a, a, g, g, g, g, a, a, l, l, l, l, l],
      [l, l, l, a, a, g, g, g, g, a, a, l, l, l, l],
      [l, l, l, l, a, g, g, g, g, g, a, l, l, l, l], 
   ],
   [
      [l, l, l, l, a, g, g, g, g, g, a, l, l, l, l],
      [l, l, l, l, a, a, g, g, g, g, a, a, l, l, l],
      [l, l, l, l, l, a, a, g, g, g, g, a, a, l, l],
      [l, l, l, l, l, l, a, a, g, g, g, g, a, a, l],
      [l, l, l, l, l, l, l, a, a, g, g, g, g, a, a],
      [l, l, l, l, l, l, l, l, a, a, g, g, g, g, g],
      [l, l, l, l, l, l, l, l, l, a, a, g, g, g, g],
      [l, l, l, l, l, l, l, l, l, l, a, a, g, g, g],
      [l, l, l, l, l, l, l, l, l, l, l, a, a, g, g],
      [l, l, l, l, l, l, l, l, l, l, l, l, a, a, g],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, a, a],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l], 
   ]

]