/* --------- colors - index --------- */
const a = 0;  // black
const b = 1;  // white
const c = 2;  // red
const d = 3;  // green
const e = 4;  // blue
const f = 5;  // yellow
const g = 6;  // #30ff3e
const h = 7;  // #00ffff
const i = 8;  // clay
const j = 9;  // samudro
const k = 10; // golden 
const l = 11; // grass
const m = 12; // like gray
const n = 13; // close to balck
const o = 14; // silver 
const p = 15; // dark silver 
/* ----------------------------------- */

const worldMap = [
   [
      [i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i],
      [i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i],
      [i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i],
      [i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i],
      [i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i],
      [i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i],
      [i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i],
      [i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i],
      [i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i],
      [i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i],
      [i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i],
      [i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i],
      [i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i],
      [i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i],
      [i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i],
      [i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i],
      [i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i],
      [i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i],
      [i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i],
      [i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i],
      [i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i]
   ],
   [
      [j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j],
      [j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j],
      [j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j],
      [j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j],
      [j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j],
      [j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j],
      [j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j],
      [j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j],
      [j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j],
      [j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j],
      [j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j],
      [j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j],
      [j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j],
      [j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j],
      [j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j],
      [j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j],
      [j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j],
      [j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j],
      [j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j],
      [j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j],
      [j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j]
   ],
   [
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l]
   ],
   [
      [i, i, i, i, i, i, i, i, i, i, a, l, l, l, l, l, l, l, l, l, l],
      [i, i, i, i, i, i, i, i, i, i, a, l, l, l, l, l, l, l, l, l, l],
      [i, i, i, i, i, i, i, i, i, i, a, l, l, l, l, l, l, l, l, l, l],
      [i, i, i, i, i, i, i, i, i, i, a, l, l, l, l, l, l, l, l, l, l],
      [i, i, i, i, i, i, i, i, i, i, a, l, l, l, l, l, l, l, l, l, l],
      [i, i, i, i, i, i, i, i, i, i, a, l, l, l, l, l, l, l, l, l, l],
      [i, i, i, i, i, i, i, i, i, i, a, l, l, l, l, l, l, l, l, l, l],
      [i, i, i, i, i, i, i, i, i, i, a, l, l, l, l, l, l, l, l, l, l],
      [i, i, i, i, i, i, i, i, i, i, a, l, l, l, l, l, l, l, l, l, l],
      [i, i, i, i, i, i, i, i, i, i, a, l, l, l, l, l, l, l, l, l, l],
      [i, i, i, i, i, i, i, i, i, i, a, l, l, l, l, l, l, l, l, l, l],
      [i, i, i, i, i, i, i, i, i, i, a, l, l, l, l, l, l, l, l, l, l],
      [i, i, i, i, i, i, i, i, i, i, a, l, l, l, l, l, l, l, l, l, l],
      [i, i, i, i, i, i, i, i, i, i, a, l, l, l, l, l, l, l, l, l, l],
      [i, i, i, i, i, i, i, i, i, i, a, l, l, l, l, l, l, l, l, l, l],
      [i, i, i, i, i, i, i, i, i, i, a, l, l, l, l, l, l, l, l, l, l],
      [i, i, i, i, i, i, i, i, i, i, a, l, l, l, l, l, l, l, l, l, l],
      [i, i, i, i, i, i, i, i, i, i, a, l, l, l, l, l, l, l, l, l, l],
      [i, i, i, i, i, i, i, i, i, i, a, l, l, l, l, l, l, l, l, l, l],
      [i, i, i, i, i, i, i, i, i, i, a, l, l, l, l, l, l, l, l, l, l],
      [i, i, i, i, i, i, i, i, i, i, a, l, l, l, l, l, l, l, l, l, l]
   ],
   [
      [l, l, l, l, l, l, l, l, l, l, a, j, j, j, j, j, j, j, j, j, j],
      [l, l, l, l, l, l, l, l, l, l, a, j, j, j, j, j, j, j, j, j, j],
      [l, l, l, l, l, l, l, l, l, l, a, j, j, j, j, j, j, j, j, j, j],
      [l, l, l, l, l, l, l, l, l, l, a, j, j, j, j, j, j, j, j, j, j],
      [l, l, l, l, l, l, l, l, l, l, a, j, j, j, j, j, j, j, j, j, j],
      [l, l, l, l, l, l, l, l, l, l, a, j, j, j, j, j, j, j, j, j, j],
      [l, l, l, l, l, l, l, l, l, l, a, j, j, j, j, j, j, j, j, j, j],
      [l, l, l, l, l, l, l, l, l, l, a, j, j, j, j, j, j, j, j, j, j],
      [l, l, l, l, l, l, l, l, l, l, a, j, j, j, j, j, j, j, j, j, j],
      [l, l, l, l, l, l, l, l, l, l, a, j, j, j, j, j, j, j, j, j, j],
      [l, l, l, l, l, l, l, l, l, l, a, j, j, j, j, j, j, j, j, j, j],
      [l, l, l, l, l, l, l, l, l, l, a, j, j, j, j, j, j, j, j, j, j],
      [l, l, l, l, l, l, l, l, l, l, a, j, j, j, j, j, j, j, j, j, j],
      [l, l, l, l, l, l, l, l, l, l, a, j, j, j, j, j, j, j, j, j, j],
      [l, l, l, l, l, l, l, l, l, l, a, j, j, j, j, j, j, j, j, j, j],
      [l, l, l, l, l, l, l, l, l, l, a, j, j, j, j, j, j, j, j, j, j],
      [l, l, l, l, l, l, l, l, l, l, a, j, j, j, j, j, j, j, j, j, j],
      [l, l, l, l, l, l, l, l, l, l, a, j, j, j, j, j, j, j, j, j, j],
      [l, l, l, l, l, l, l, l, l, l, a, j, j, j, j, j, j, j, j, j, j],
      [l, l, l, l, l, l, l, l, l, l, a, j, j, j, j, j, j, j, j, j, j],
      [l, l, l, l, l, l, l, l, l, l, a, j, j, j, j, j, j, j, j, j, j]
   ],
   [
      [i, i, i, i, i, i, i, i, i, i, a, l, l, l, l, l, l, l, l, l, l],
      [i, i, i, i, i, i, i, i, i, i, a, l, l, l, l, l, l, l, l, l, l],
      [i, i, i, i, i, i, i, i, i, i, a, l, l, l, l, l, l, l, l, l, l],
      [i, i, i, i, i, i, i, i, i, i, a, l, l, l, l, l, l, l, l, l, l],
      [i, i, i, i, i, i, i, i, i, a, a, l, l, l, l, l, l, l, l, l, l],
      [i, i, i, i, i, i, i, i, i, a, l, l, l, l, l, l, l, l, l, l, l],
      [i, i, i, i, i, i, i, i, a, a, l, l, l, l, l, l, l, l, l, l, l],
      [i, i, i, i, i, i, i, a, a, l, l, l, l, l, l, l, l, l, l, l, l],
      [i, i, i, i, i, i, a, a, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [i, i, i, i, a, a, a, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [a, a, a, a, a, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l]
   ],
   [
      [j, j, j, j, j, j, j, j, j, j, a, l, l, l, l, l, l, l, l, l, l],
      [j, j, j, j, j, j, j, j, j, j, a, l, l, l, l, l, l, l, l, l, l],
      [j, j, j, j, j, j, j, j, j, j, a, l, l, l, l, l, l, l, l, l, l],
      [j, j, j, j, j, j, j, j, j, j, a, l, l, l, l, l, l, l, l, l, l],
      [j, j, j, j, j, j, j, j, j, a, a, l, l, l, l, l, l, l, l, l, l],
      [j, j, j, j, j, j, j, j, j, a, l, l, l, l, l, l, l, l, l, l, l],
      [j, j, j, j, j, j, j, j, a, a, l, l, l, l, l, l, l, l, l, l, l],
      [j, j, j, j, j, j, j, a, a, l, l, l, l, l, l, l, l, l, l, l, l],
      [j, j, j, j, j, j, a, a, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [j, j, j, j, a, a, a, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [a, a, a, a, a, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l]
   ],
   [
      [l, l, l, l, l, l, l, l, l, l, a, j, j, j, j, j, j, j, j, j, j],
      [l, l, l, l, l, l, l, l, l, l, a, j, j, j, j, j, j, j, j, j, j],
      [l, l, l, l, l, l, l, l, l, l, a, j, j, j, j, j, j, j, j, j, j],
      [l, l, l, l, l, l, l, l, l, l, a, j, j, j, j, j, j, j, j, j, j],
      [l, l, l, l, l, l, l, l, l, a, a, j, j, j, j, j, j, j, j, j, j],
      [l, l, l, l, l, l, l, l, l, a, j, j, j, j, j, j, j, j, j, j, j],
      [l, l, l, l, l, l, l, l, a, a, j, j, j, j, j, j, j, j, j, j, j],
      [l, l, l, l, l, l, l, a, a, j, j, j, j, j, j, j, j, j, j, j, j],
      [l, l, l, l, l, l, a, a, j, j, j, j, j, j, j, j, j, j, j, j, j],
      [l, l, l, l, a, a, a, j, j, j, j, j, j, j, j, j, j, j, j, j, j],
      [a, a, a, a, a, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j],
      [j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j],
      [j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j],
      [j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j],
      [j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j],
      [j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j],
      [j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j],
      [j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j],
      [j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j],
      [j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j],
      [j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j]
   ],
   [
      [l, l, l, l, l, l, l, l, l, l, a, j, j, j, j, j, j, j, j, j, j],
      [l, l, l, l, l, l, l, l, l, l, a, j, j, j, j, j, j, j, j, j, j],
      [l, l, l, l, l, l, l, l, l, l, a, j, j, j, j, j, j, j, j, j, j],
      [l, l, l, l, l, l, l, l, l, l, a, j, j, j, j, j, j, j, j, j, j],
      [l, l, l, l, l, l, l, l, l, a, a, j, j, j, j, j, j, j, j, j, j],
      [l, l, l, l, l, l, l, l, l, a, j, j, j, j, j, j, j, j, j, j, j],
      [l, l, l, l, l, l, l, l, a, a, j, j, j, j, j, j, j, j, j, j, j],
      [l, l, l, l, l, l, l, a, a, j, j, j, j, j, j, j, j, j, j, j, j],
      [l, l, l, l, l, l, a, a, j, j, j, j, j, j, j, j, j, j, j, j, j],
      [l, l, l, l, a, a, a, j, j, j, j, j, j, j, j, j, j, j, j, j, j],
      [a, a, a, a, a, j, j, j, j, j, j, j, j, j, j, j, a, a, a, a, a],
      [j, j, j, j, j, j, j, j, j, j, j, j, j, j, a, a, a, l, l, l, l],
      [j, j, j, j, j, j, j, j, j, j, j, j, j, a, a, l, l, l, l, l, l],
      [j, j, j, j, j, j, j, j, j, j, j, j, a, a, l, l, l, l, l, l, l],
      [j, j, j, j, j, j, j, j, j, j, j, a, a, l, l, l, l, l, l, l, l],
      [j, j, j, j, j, j, j, j, j, j, j, a, l, l, l, l, l, l, l, l, l],
      [j, j, j, j, j, j, j, j, j, j, a, a, l, l, l, l, l, l, l, l, l],
      [j, j, j, j, j, j, j, j, j, j, a, l, l, l, l, l, l, l, l, l, l],
      [j, j, j, j, j, j, j, j, j, j, a, l, l, l, l, l, l, l, l, l, l],
      [j, j, j, j, j, j, j, j, j, j, a, l, l, l, l, l, l, l, l, l, l],
      [j, j, j, j, j, j, j, j, j, j, a, l, l, l, l, l, l, l, l, l, l]
   ],
   [
      [l, l, l, l, l, l, l, l, l, l, a, i, i, i, i, i, i, i, i, i, i],
      [l, l, l, l, l, l, l, l, l, l, a, i, i, i, i, i, i, i, i, i, i],
      [l, l, l, l, l, l, l, l, l, l, a, i, i, i, i, i, i, i, i, i, i],
      [l, l, l, l, l, l, l, l, l, l, a, i, i, i, i, i, i, i, i, i, i],
      [l, l, l, l, l, l, l, l, l, a, a, i, i, i, i, i, i, i, i, i, i],
      [l, l, l, l, l, l, l, l, l, a, i, i, i, i, i, i, i, i, i, i, i],
      [l, l, l, l, l, l, l, l, a, a, i, i, i, i, i, i, i, i, i, i, i],
      [l, l, l, l, l, l, l, a, a, i, i, i, i, i, i, i, i, i, i, i, i],
      [l, l, l, l, l, l, a, a, i, i, i, i, i, i, i, i, i, i, i, i, i],
      [l, l, l, l, a, a, a, i, i, i, i, i, i, i, i, i, i, i, i, i, i],
      [a, a, a, a, a, i, i, i, i, i, i, i, i, i, i, i, a, a, a, a, a],
      [i, i, i, i, i, i, i, i, i, i, i, i, i, i, a, a, a, l, l, l, l],
      [i, i, i, i, i, i, i, i, i, i, i, i, i, a, a, l, l, l, l, l, l],
      [i, i, i, i, i, i, i, i, i, i, i, i, a, a, l, l, l, l, l, l, l],
      [i, i, i, i, i, i, i, i, i, i, i, a, a, l, l, l, l, l, l, l, l],
      [i, i, i, i, i, i, i, i, i, i, i, a, l, l, l, l, l, l, l, l, l],
      [i, i, i, i, i, i, i, i, i, i, a, a, l, l, l, l, l, l, l, l, l],
      [i, i, i, i, i, i, i, i, i, i, a, l, l, l, l, l, l, l, l, l, l],
      [i, i, i, i, i, i, i, i, i, i, a, l, l, l, l, l, l, l, l, l, l],
      [i, i, i, i, i, i, i, i, i, i, a, l, l, l, l, l, l, l, l, l, l],
      [i, i, i, i, i, i, i, i, i, i, a, l, l, l, l, l, l, l, l, l, l]
   ],
   [
      [j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j],
      [j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j],
      [j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j],
      [j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j],
      [j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j],
      [j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j],
      [j, j, j, j, j, j, j, j, j, j, p, j, j, j, j, j, j, j, j, j, j],
      [p, p, p, p, p, p, p, p, p, p, p, p, p, p, p, p, p, p, p, p, p],
      [o, o, o, o, o, o, o, o, o, o, o, o, o, o, o, o, o, o, o, o, o],
      [o, o, o, o, o, o, o, o, o, o, o, o, o, o, o, o, o, o, o, o, o],
      [o, o, o, o, o, o, o, o, o, o, o, o, o, o, o, o, o, o, o, o, o],
      [o, o, o, o, o, o, o, o, o, o, o, o, o, o, o, o, o, o, o, o, o],
      [o, o, o, o, o, o, o, o, o, o, o, o, o, o, o, o, o, o, o, o, o],
      [p, p, p, p, p, p, p, p, p, p, p, p, p, p, p, p, p, p, p, p, p],
      [j, j, j, j, j, j, j, j, j, j, p, j, j, j, j, j, j, j, j, j, j],
      [j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j],
      [j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j],
      [j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j],
      [j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j],
      [j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j],
      [j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j, j]
   ],
   [
      [l, l, l, l, l, l, l, l, l, l, a, j, j, j, j, j, j, j, j, j, j],
      [l, l, l, l, l, l, l, l, l, l, a, j, j, j, j, j, j, j, j, j, j],
      [l, l, l, l, l, l, l, l, l, l, a, j, j, j, j, j, j, j, j, j, j],
      [l, l, l, l, l, l, l, l, l, l, a, j, j, j, j, j, j, j, j, j, j],
      [l, l, l, l, l, l, l, l, l, l, a, j, j, j, j, j, j, j, j, j, j],
      [l, l, l, l, l, l, l, l, l, l, a, j, j, j, j, j, j, j, j, j, j],
      [l, l, l, l, l, l, l, l, l, p, p, p, j, j, j, j, j, j, j, j, j],
      [l, l, l, l, o, o, o, o, p, p, p, p, p, p, p, p, p, p, p, p, p],
      [l, l, l, o, o, o, o, o, o, o, o, o, o, o, o, o, o, o, o, o, o],
      [l, l, o, o, o, o, o, o, o, o, o, o, o, o, o, o, o, o, o, o, o],
      [l, l, o, o, o, o, o, o, o, o, o, o, o, o, o, o, o, o, o, o, o],
      [l, l, o, o, o, o, o, o, o, o, o, o, o, o, o, o, o, o, o, o, o],
      [l, l, l, o, o, o, o, o, o, o, o, o, o, o, o, o, o, o, o, o, o],
      [l, l, l, l, o, o, o, o, p, p, p, p, p, p, p, p, p, p, p, p, p],
      [l, l, l, l, l, l, l, l, l, p, p, p, j, j, j, j, j, j, j, j, j],
      [l, l, l, l, l, l, l, l, l, l, a, j, j, j, j, j, j, j, j, j, j],
      [l, l, l, l, l, l, l, l, l, l, a, j, j, j, j, j, j, j, j, j, j],
      [l, l, l, l, l, l, l, l, l, l, a, j, j, j, j, j, j, j, j, j, j],
      [l, l, l, l, l, l, l, l, l, l, a, j, j, j, j, j, j, j, j, j, j],
      [l, l, l, l, l, l, l, l, l, l, a, j, j, j, j, j, j, j, j, j, j],
      [l, l, l, l, l, l, l, l, l, l, a, j, j, j, j, j, j, j, j, j, j]
   ]
]

const PCBMap = [
   [
      [n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n],
      [n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n],
      [n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n],
      [n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n],
      [n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n],
      [n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n],
      [n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n],
      [n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n],
      [n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n],
      [n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n],
      [n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n],
      [n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n],
      [n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n],
      [n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n],
      [n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n],
      [n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n],
      [n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n],
      [n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n],
      [n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n],
      [n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n],
      [n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n],
   ],
   [
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
   ],
   [
      [n, n, n, a, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [n, n, n, a, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [n, n, n, a, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [a, a, a, a, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
   ],
   [                                //
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, a, a, a, a, a, a, a, l, l, l, l, l, l, l],
      [l, l, l, l, l, a, a, a, m, m, m, m, m, a, a, a, l, l, l, l, l],
      [l, l, l, l, a, a, m, m, m, m, m, m, m, m, m, a, a, l, l, l, l],
      [l, l, l, a, a, m, m, m, m, m, m, m, m, m, m, m, a, a, l, l, l],
      [l, l, l, a, m, m, m, m, m, m, m, m, m, m, m, m, m, a, a, a, a],
      [l, l, a, a, m, m, m, m, m, m, m, m, m, m, m, m, m, m, m, p, g],
      [l, l, a, m, m, m, m, m, m, m, m, m, m, m, m, m, m, m, m, p, g],
      [l, l, a, m, m, m, m, m, m, m, m, m, m, m, m, m, m, m, m, p, g],
      [l, l, a, m, m, m, m, m, m, m, m, m, m, m, m, m, m, m, m, p, g], //
      [l, l, a, m, m, m, m, m, m, m, m, m, m, m, m, m, m, m, m, p, g],
      [l, l, a, m, m, m, m, m, m, m, m, m, m, m, m, m, m, m, m, p, g],
      [l, l, a, a, m, m, m, m, m, m, m, m, m, m, m, m, m, m, m, p, g],
      [l, l, l, a, m, m, m, m, m, m, m, m, m, m, m, m, m, a, a, a, a],
      [l, l, l, a, a, m, m, m, m, m, m, m, m, m, m, m, a, a, l, l, l],
      [l, l, l, l, a, a, m, m, m, m, m, m, m, m, m, a, a, l, l, l, l],
      [l, l, l, l, l, a, a, a, m, m, m, m, m, a, a, a, l, l, l, l, l],
      [l, l, l, l, l, l, l, a, a, a, a, a, a, a, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
   ],
   [                                //
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, a, a, a, a, a, a, a, l, l, l, l, l, l, l],
      [l, l, l, l, l, a, a, a, m, m, m, m, m, a, a, a, l, l, l, l, l],
      [l, l, l, l, a, a, m, m, m, m, m, m, m, m, m, a, a, l, l, l, l],
      [l, l, l, a, a, m, m, m, m, m, m, m, m, m, m, m, a, a, l, l, l],
      [a, a, a, a, m, m, m, m, m, m, m, m, m, m, m, m, m, a, a, a, a],
      [g, p, m, m, m, m, m, m, m, m, m, m, m, m, m, m, m, m, m, p, g],
      [g, p, m, m, m, m, m, m, m, m, m, m, m, m, m, m, m, m, m, p, g],
      [g, p, m, m, m, m, m, m, m, m, m, m, m, m, m, m, m, m, m, p, g],
      [g, p, m, m, m, m, m, m, m, m, m, m, m, m, m, m, m, m, m, p, g], //
      [g, p, m, m, m, m, m, m, m, m, m, m, m, m, m, m, m, m, m, p, g],
      [g, p, m, m, m, m, m, m, m, m, m, m, m, m, m, m, m, m, m, p, g],
      [g, p, m, m, m, m, m, m, m, m, m, m, m, m, m, m, m, m, m, p, g],
      [a, a, a, a, m, m, m, m, m, m, m, m, m, m, m, m, m, a, a, a, a],
      [l, l, l, a, a, m, m, m, m, m, m, m, m, m, m, m, a, a, l, l, l],
      [l, l, l, l, a, a, m, m, m, m, m, m, m, m, m, a, a, l, l, l, l],
      [l, l, l, l, l, a, a, a, m, m, m, m, m, a, a, a, l, l, l, l, l],
      [l, l, l, l, l, l, l, a, a, a, a, a, a, a, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
   ],
   [                                 //
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a],
      [m, m, m, m, m, m, m, m, m, m, m, m, m, m, m, m, m, m, m, m, m],
      [m, m, m, m, m, m, m, m, m, m, m, m, m, m, m, m, m, m, m, m, m],
      [m, m, m, m, m, m, m, m, m, m, m, m, m, m, m, m, m, m, m, m, m],
      [m, m, m, m, m, m, m, m, m, m, m, m, m, m, m, m, m, m, m, m, m],
      [m, m, m, m, m, m, m, m, m, m, m, m, m, m, m, m, m, m, m, m, m], //
      [m, m, m, m, m, m, m, m, m, m, m, m, m, m, m, m, m, m, m, m, m],
      [m, m, m, m, m, m, m, m, m, m, m, m, m, m, m, m, m, m, m, m, m],
      [a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
   ],
   [                                 //
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a],
      [g, g, g, g, g, g, g, g, g, g, g, g, g, g, g, g, g, g, g, g, g],
      [g, g, g, g, g, g, g, g, g, g, g, g, g, g, g, g, g, g, g, g, g],
      [g, g, g, g, g, g, g, g, g, g, g, g, g, g, g, g, g, g, g, g, g],
      [g, g, g, g, g, g, g, g, g, g, g, g, g, g, g, g, g, g, g, g, g], //
      [g, g, g, g, g, g, g, g, g, g, g, g, g, g, g, g, g, g, g, g, g],
      [g, g, g, g, g, g, g, g, g, g, g, g, g, g, g, g, g, g, g, g, g],
      [g, g, g, g, g, g, g, g, g, g, g, g, g, g, g, g, g, g, g, g, g],
      [a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
   ],
   [                                 // 
      [l, l, l, l, l, l, a, g, g, g, g, g, g, g, a, l, l, l, l, l, l],
      [l, l, l, l, l, l, a, g, g, g, g, g, g, g, a, l, l, l, l, l, l],
      [l, l, l, l, l, l, a, g, g, g, g, g, g, g, a, l, l, l, l, l, l],
      [l, l, l, l, l, l, a, g, g, g, g, g, g, g, a, l, l, l, l, l, l],
      [l, l, l, l, l, l, a, g, g, g, g, g, g, g, a, l, l, l, l, l, l],
      [l, l, l, l, l, l, a, g, g, g, g, g, g, g, a, l, l, l, l, l, l],
      [a, a, a, a, a, a, a, g, g, g, g, g, g, g, a, a, a, a, a, a, a],
      [g, g, g, g, g, g, g, g, g, g, g, g, g, g, g, g, g, g, g, g, g],
      [g, g, g, g, g, g, g, g, g, g, g, g, g, g, g, g, g, g, g, g, g],
      [g, g, g, g, g, g, g, g, g, g, g, g, g, g, g, g, g, g, g, g, g],
      [g, g, g, g, g, g, g, g, g, g, g, g, g, g, g, g, g, g, g, g, g], //
      [g, g, g, g, g, g, g, g, g, g, g, g, g, g, g, g, g, g, g, g, g],
      [g, g, g, g, g, g, g, g, g, g, g, g, g, g, g, g, g, g, g, g, g],
      [g, g, g, g, g, g, g, g, g, g, g, g, g, g, g, g, g, g, g, g, g],
      [a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
   ],
   [                                 // 
      [l, l, l, l, l, l, a, m, m, m, m, m, m, m, a, l, l, l, l, l, l],
      [l, l, l, l, l, l, a, m, m, m, m, m, m, m, a, l, l, l, l, l, l],
      [l, l, l, l, l, l, a, m, m, m, m, m, m, m, a, l, l, l, l, l, l],
      [l, l, l, l, l, l, a, m, m, m, m, m, m, m, a, l, l, l, l, l, l],
      [l, l, l, l, l, l, a, m, m, m, m, m, m, m, a, l, l, l, l, l, l],
      [l, l, l, l, l, l, a, m, m, m, m, m, m, m, a, l, l, l, l, l, l],
      [a, a, a, a, a, a, a, m, m, m, m, m, m, m, a, a, a, a, a, a, a],
      [g, g, g, g, g, g, a, m, m, m, m, m, m, m, a, g, g, g, g, g, g],
      [g, g, g, g, g, g, a, m, m, m, m, m, m, m, a, g, g, g, g, g, g],
      [g, g, g, g, g, g, a, m, m, m, m, m, m, m, a, g, g, g, g, g, g],
      [g, g, g, g, g, g, a, m, m, m, m, m, m, m, a, g, g, g, g, g, g], //
      [g, g, g, g, g, g, a, m, m, m, m, m, m, m, a, g, g, g, g, g, g],
      [g, g, g, g, g, g, a, m, m, m, m, m, m, m, a, g, g, g, g, g, g],
      [g, g, g, g, g, g, a, m, m, m, m, m, m, m, a, g, g, g, g, g, g],
      [a, a, a, a, a, a, a, m, m, m, m, m, m, m, a, a, a, a, a, a, a],
      [l, l, l, l, l, l, a, m, m, m, m, m, m, m, a, l, l, l, l, l, l],
      [l, l, l, l, l, l, a, m, m, m, m, m, m, m, a, l, l, l, l, l, l],
      [l, l, l, l, l, l, a, m, m, m, m, m, m, m, a, l, l, l, l, l, l],
      [l, l, l, l, l, l, a, m, m, m, m, m, m, m, a, l, l, l, l, l, l],
      [l, l, l, l, l, l, a, m, m, m, m, m, m, m, a, l, l, l, l, l, l],
      [l, l, l, l, l, l, a, m, m, m, m, m, m, m, a, l, l, l, l, l, l],
   ],
   [                                 //
      [n, n, n, a, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [n, n, n, a, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [n, n, n, a, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [n, n, n, a, a, a, a, a, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [n, n, n, a, m, m, m, a, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [n, n, n, a, m, m, m, a, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [n, n, n, a, m, m, m, a, a, a, a, a, a, a, a, a, a, a, a, a, a],
      [n, n, n, a, m, m, m, a, m, m, m, m, m, m, m, m, a, g, g, g, g],
      [n, n, n, a, m, m, m, a, m, m, m, m, m, m, m, m, a, g, g, g, g],
      [n, n, n, a, m, m, m, a, m, m, m, m, m, m, m, m, a, g, g, g, g],
      [n, n, n, a, m, m, m, a, m, m, m, m, m, m, m, m, a, g, g, g, g], //
      [n, n, n, a, m, m, m, a, m, m, m, m, m, m, m, m, a, g, g, g, g],
      [n, n, n, a, m, m, m, a, m, m, m, m, m, m, m, m, a, g, g, g, g],
      [n, n, n, a, m, m, m, a, m, m, m, m, m, m, m, m, a, g, g, g, g],
      [n, n, n, a, m, m, m, a, a, a, a, a, a, a, a, a, a, a, a, a, a],
      [n, n, n, a, m, m, m, a, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [n, n, n, a, m, m, m, a, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [n, n, n, a, a, a, a, a, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [n, n, n, a, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [n, n, n, a, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [n, n, n, a, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
   ],
   [                                //
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, a, a, a, a, a, a, a, l, l, l, l, l, l, l],
      [l, l, l, l, l, a, a, a, m, m, m, m, m, a, a, a, l, l, l, l, l],
      [l, l, l, l, a, a, m, m, m, m, m, m, m, m, m, a, a, l, l, l, l],
      [l, l, l, a, a, p, p, p, p, p, p, p, p, p, m, m, a, a, l, l, l],
      [a, a, a, a, a, a, a, a, a, a, a, a, a, p, m, m, m, a, a, a, a],
      [m, m, m, m, m, m, m, m, m, m, m, m, m, m, m, m, m, m, p, g, g],
      [m, m, m, m, m, m, m, m, m, m, m, m, m, m, m, m, m, m, p, g, g],
      [m, m, m, m, m, m, m, m, m, m, m, m, m, m, m, m, m, m, p, g, g],
      [m, m, m, m, m, m, m, m, m, m, m, m, m, m, m, m, m, m, p, g, g], //
      [m, m, m, m, m, m, m, m, m, m, m, m, m, m, m, m, m, m, p, g, g],
      [m, m, m, m, m, m, m, m, m, m, m, m, m, m, m, m, m, m, p, g, g],
      [m, m, m, m, m, m, m, m, m, m, m, m, m, m, m, m, m, m, p, g, g],
      [a, a, a, a, a, a, a, a, a, a, a, a, a, p, m, m, m, a, a, a, a],
      [l, l, l, a, a, p, p, p, p, p, p, p, p, p, m, m, a, a, l, l, l],
      [l, l, l, l, a, a, m, m, m, m, m, m, m, m, m, a, a, l, l, l, l],
      [l, l, l, l, l, a, a, a, m, m, m, m, m, a, a, a, l, l, l, l, l],
      [l, l, l, l, l, l, l, a, a, a, a, a, a, a, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
   ],
   [                                 // 
      [l, l, l, l, l, l, a, g, g, g, g, g, g, g, a, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, a, g, g, g, g, g, g, g, a, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, a, g, g, g, g, g, g, g, a, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, a, g, g, g, g, g, g, g, a, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, a, g, g, g, g, g, g, g, a, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, a, g, g, g, g, g, g, g, a, l],
      [a, l, l, l, l, l, l, l, l, l, l, l, a, g, g, g, g, g, g, g, a],
      [g, a, l, l, l, l, l, l, l, l, l, l, l, a, g, g, g, g, g, g, g],
      [g, g, a, l, l, l, l, l, l, l, l, l, l, l, a, g, g, g, g, g, g],
      [g, g, g, a, l, l, l, l, l, l, l, l, l, l, l, a, g, g, g, g, g],
      [g, g, g, g, a, l, l, l, l, l, l, l, l, l, l, l, a, g, g, g, g], //
      [g, g, g, g, g, a, l, l, l, l, l, l, l, l, l, l, l, a, g, g, g],
      [g, g, g, g, g, g, a, l, l, l, l, l, l, l, l, l, l, l, a, g, g],
      [g, g, g, g, g, g, g, a, l, l, l, l, l, l, l, l, l, l, l, a, g],
      [a, g, g, g, g, g, g, g, a, l, l, l, l, l, l, l, l, l, l, l, a],
      [l, a, g, g, g, g, g, g, g, a, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, a, g, g, g, g, g, g, g, a, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, a, g, g, g, g, g, g, g, a, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, a, g, g, g, g, g, g, g, a, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, a, g, g, g, g, g, g, g, a, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, a, g, g, g, g, g, g, g, a, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, a, g, g, g, g, g, g, g, a, l, l, l, l, l],
   ],
   [                                 // 
      [l, l, l, l, l, l, a, g, g, g, g, g, g, g, a, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, a, g, g, g, g, g, g, g, a, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, a, g, g, g, g, g, g, g, a, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, a, g, g, g, g, g, g, g, a, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, a, g, g, g, g, g, g, g, a, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, a, g, g, g, g, g, g, g, a, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, a, g, g, g, g, g, g, g, a],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, a, g, g, g, g, g, g, g],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, a, g, g, g, g, g, g],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, a, g, g, g, g, g],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, a, g, g, g, g], //
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, a, g, g, g],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, a, g, g],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, a, g],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, a],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
      [l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l, l],
   ],


]
